apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansimspring-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: AnsimSpring
  template:
    metadata:
      name: AnsimSpring
      labels:
        app: AnsimSpring
    spec:
      containers:
      - name: AnsimSpring
        image: docker.io/yjy8606/ansimspring_ansimspring:{{VERSION}}
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: ansimspring-secret

---
apiVersion: v1
kind: Service
metadata:
  name: ansimspring-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
  selector:
    app: AnsimSpring
  type: NodePort
